server:
  port: 8081
spring:
  application:
    name: @artifactId@
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output2:
            producer:
              transactional: true
              group: myTxproduceGroup #事务分组
      bindings:
        output1:
          destination: test-topic
          content-type: application/json
        output2:
          destination: transaction-topic
          content-type: application/json
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always #显示服务信息详情
