jwt:
  subject:
    name: czs-admin
  secret:
    key: online-runaccepted
  expire:
    time: 12000
  user:
    format: CZS_JWT_USERNAME::%s
  token:
    format: CZS_JWT_TOKEN
  blacklist:
    format: CZS_JWT_BLACKLIST::%s  #令牌黑名单，用于用户注销/登出/修改账号密码时
  #redis
  spring:
    redis:
      host: localhost
      port: 6379